name: 'Update Branches'
description: 'Update beta if staging receive push'

inputs:
  target_branch:
    description: 'The name of target branch to merge'
    required: true
  from_branch:
    description: 'Alias head_to_merge input'
    required: false
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'